services:
  - type: web
    name: peopleofanioma
    env: python
    plan: free
    buildCommand: |
      pip install -r backend/requirements.txt
      python backend/manage.py collectstatic --noinput
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: SECRET_KEY
        value: your-secret-key
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: yourdomain.com,render.com
      - key: DATABASE_URL
        fromDatabase:
          name: your-database-name
          property: connectionString
