# Generated by Django 5.0.14 on 2026-01-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='video_file',
            field=models.URLField(blank=True, help_text='S3 or external video URL (YouTube, Vimeo, etc.)', null=True),
        ),
    ]
