# Generated by Django 5.2 on 2025-06-12 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_tag_name_comment_reaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="category",
            field=models.CharField(
                choices=[
                    ("history", "History"),
                    ("events", "Events"),
                    ("lifestyle", "Lifestyle"),
                    ("tradition", "Tradition"),
                    ("culture", "Culture"),
                    ("entertainment", "Entertainment"),
                    ("news", "News"),
                    ("business", "Business"),
                    ("literature", "Literature"),
                    ("technology", "Technology"),
                    ("sports", "Sports"),
                    ("spotlight", "Spotlight"),
                ],
                default="news",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="reaction",
            name="blog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions",
                to="blog.blog",
            ),
        ),
    ]
