# Generated by Django 5.2 on 2025-05-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EthnographicSurvey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("occupation", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("cultural_practice", models.TextField()),
                ("oral_history", models.TextField(blank=True, null=True)),
                ("language_spoken", models.CharField(max_length=100)),
                ("date_submitted", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
