# Generated by Django 5.2 on 2025-05-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ethnographic_survey", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ethnographicsurvey",
            name="local_origin",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Aniocha North", "Aniocha North"),
                    ("Aniocha South", "Aniocha South"),
                    ("Ndokwa East", "Ndokwa East"),
                    ("Ndokwa West", "Ndokwa West"),
                    ("Oshimili North", "Oshimili North"),
                    ("Oshimili South", "Oshimili South"),
                    ("Ukwuani", "Ukwuani"),
                    ("Ika North East", "Ika North East"),
                    ("Ika South", "Ika South"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="ethnographicsurvey",
            name="village",
            field=models.CharField(default="unknown", max_length=100),
        ),
    ]
