# Generated by Django 5.2 on 2025-05-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ethnographic_survey", "0002_ethnographicsurvey_local_origin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ethnographicsurvey",
            name="village",
            field=models.CharField(default="Please specify", max_length=100),
        ),
    ]
