# Generated by Django 5.2 on 2025-05-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ethnographic_survey", "0003_alter_ethnographicsurvey_village"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ethnographicsurvey",
            name="village",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
