# Generated by Django 5.0.14 on 2026-01-11 16:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SemanticPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pattern_type', models.CharField(choices=[('keyword', 'Keyword'), ('phrase', 'Phrase'), ('entity', 'Named Entity'), ('topic', 'Topic Cluster'), ('location', 'Location'), ('cultural', 'Cultural Concept')], max_length=50)),
                ('pattern', models.TextField()),
                ('weight', models.FloatField(default=1.0)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('source_type', models.CharField(choices=[('website', 'Website/Blog'), ('twitter', 'Twitter/X'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('reddit', 'Reddit'), ('youtube', 'YouTube'), ('telegram', 'Telegram'), ('linkedin', 'LinkedIn'), ('news_aggregator', 'News Aggregator')], max_length=50)),
                ('platform_specific_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('check_interval', models.IntegerField(default=15)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('url', 'source_type')},
            },
        ),
        migrations.CreateModel(
            name='TrackedNewsItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('url', models.URLField(max_length=1000, unique=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('published_date', models.DateTimeField()),
                ('scraped_date', models.DateTimeField(auto_now_add=True)),
                ('platform_specific_data', models.JSONField(default=dict)),
                ('categories', models.JSONField(default=list)),
                ('keywords', models.JSONField(default=list)),
                ('entities', models.JSONField(default=dict)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('relevance_score', models.FloatField(default=0.0)),
                ('is_anioma_related', models.BooleanField(default=False)),
                ('semantic_tags', models.JSONField(default=list)),
                ('content_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, default='low', max_length=10)),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('has_been_notified', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('requires_followup', models.BooleanField(default=False)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_items', to='media_intelligence.newssource')),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(max_length=50)),
                ('sent_to', models.CharField(max_length=255)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('response', models.JSONField(blank=True, default=dict)),
                ('news_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_intelligence.trackednewsitem')),
            ],
        ),
        migrations.AddIndex(
            model_name='trackednewsitem',
            index=models.Index(fields=['published_date'], name='media_intel_publish_97dc29_idx'),
        ),
        migrations.AddIndex(
            model_name='trackednewsitem',
            index=models.Index(fields=['relevance_score'], name='media_intel_relevan_58f635_idx'),
        ),
        migrations.AddIndex(
            model_name='trackednewsitem',
            index=models.Index(fields=['is_anioma_related'], name='media_intel_is_anio_891418_idx'),
        ),
    ]
