# Generated by Django 5.0.14 on 2026-01-16 15:26

from django.db import migrations


def fix_source_types(apps, schema_editor):
    NewsSource = apps.get_model("media_intelligence", "NewsSource")

    # Normalize RSS sources
    NewsSource.objects.filter(
        source_type__in=["rss", "rss_feed"]
    ).update(source_type="website")

    # Normalize Facebook sources
    NewsSource.objects.filter(
        source_type__icontains="facebook"
    ).update(source_type="facebook")


class Migration(migrations.Migration):

    dependencies = [
        ("media_intelligence", "0001_initial"),  # keep existing dependency
    ]

    operations = [
        migrations.RunPython(fix_source_types),
    ]

