# Generated by Django 5.0.14 on 2026-01-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_intelligence', '0002_fix_source_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newssource',
            name='source_type',
            field=models.CharField(choices=[('website', 'Website / RSS'), ('twitter', 'Twitter / X'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('reddit', 'Reddit'), ('youtube', 'YouTube'), ('telegram', 'Telegram'), ('linkedin', 'LinkedIn'), ('news_aggregator', 'News Aggregator')], max_length=50),
        ),
    ]
