# Generated by Django 5.0.14 on 2026-01-16 22:39

from django.db import migrations

def normalize_sources(apps, schema_editor):
    NewsSource = apps.get_model("media_intelligence", "NewsSource")

    for src in NewsSource.objects.all():
        st = (src.source_type or "").lower()

        if st in ["rss_feed", "rss"]:
            src.source_type = "rss"
        elif st.startswith("facebook"):
            src.source_type = "facebook"
        elif st.startswith("tiktok"):
            src.source_type = "tiktok"
        elif st.startswith("twitter") or st == "x":
            src.source_type = "twitter"
        elif st in ["website", "web"]:
            src.source_type = "website"

        src.save(update_fields=["source_type"])

class Migration(migrations.Migration):

    dependencies = [
        ("media_intelligence", "0003_alter_newssource_source_type"),
    ]

    operations = [
        migrations.RunPython(normalize_sources),
    ]









