# Generated by Django 5.2 on 2025-06-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("author_name", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("category", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="story_images/"),
                ),
                (
                    "audio",
                    models.FileField(blank=True, null=True, upload_to="story_audio/"),
                ),
                ("is_approved", models.BooleanField(default=False)),
                ("date_submitted", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
