# Generated by Django 5.2 on 2025-06-02 15:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_stories", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="upvotes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
