# Generated by Django 5.2 on 2025-07-01 10:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_remove_story_likes_reaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='upvotes',
        ),
        migrations.AlterUniqueTogether(
            name='reaction',
            unique_together={('user', 'story', 'type')},
        ),
    ]
