# Generated by Django 5.2 on 2025-07-01 11:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0008_remove_story_upvotes_alter_reaction_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reaction',
            new_name='StoryReaction',
        ),
    ]
